language: generic
os:
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: II1Gsmz7Q7W1Ipk10a/NXqcviP71DMRewvRNj/XKwOSPXFX9h3J4Yd9ezCfVEWjUqY9mw75/eoM3+mbw0E1lYcUp6ogkhM+q+igV75KEDgibSKCWT88F+jKT7hPz7Fa46MjSJprEqwS8z9Pp22damgUA2Acdur0PAYxoUwm/e7ccBMymVigkbTjnGj4owP4vD5NPE8qdHbXn8Eq9KdEttm9ZAgAPa09lJv9YvCGds+aYsjwEMmrNHu1j3qDWZEueVdrPi3Kb1IBT0TAOnhU875Icv5L1Lecb1t1pHSCM69sBuU32JvxQaE33VuJm9nWVZGM5NjXFJ15RW5f8D85XgU1QRiMup6I6Ikt9OvwD+jb9jtCmyD6CYOyv6vLplNcZKz4KzH7oBrtK7Arz2/zLJamlj1Gn0nfMFwdKQ+/YamzxZMZwtiTwsM5B+IErDGCQOio5vocW0rf6niPcQNxnoAhiK2ie1Gcckbe6URU7XsAt2rwJcBvhT8N+MfPwWO/fKW9iSNTVViPfgbrqxuF5Luw/9hjvxeRxuIVxTwtE74ZzIEwkPNCTeiO1eXcw/KUDK/0yxWaUpQwgKSGviy4/laxavAe77/TJdZDKzyL7J01D6HS5JUjLB+nWM3Zg8AnOeouOwctMr9yvDIh3lffYEQvBiN6QFQflU25KRRII9E0=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
